### ISSUE TITLE
IURI set-query-params impl for URI has different behaviour to that of URL

### ISSUE THREAD

**Issue by scottlowe** [Swirrl/grafter-url#5]
`set-query-params` on URL will not touch encoded characters; but for URI, it will.

Le sigh.

Observe:

```clojure
    (def params [["http%3A%2F%2Ffoo" "http%3A%2F%2Fbar"]])

    (-> (URI. "http://x.com/")
        (url/set-query-params params))

    (-> (URL. "http://x.com/")
        (url/set-query-params params))

    ; => #object[java.net.URI 0x53a76152 "http://x.com/?http%253A%252F%252Ffoo=http%253A%252F%252Fbar"]
    ; => #object[java.net.URL 0x39f91993 "http://x.com/?http%3A%2F%2Ffoo=http%3A%2F%2Fbar"]
```

**Comment by RickMoynihan** [comment]
The general case of this with java.net.URI is basically unfixable as the problem lies in java.net.URI which actively prevents you from doing the right thing: https://blog.stackhunter.com/2014/03/31/encode-special-characters-java-net-uri/

**Comment by ricroberts** [comment]
adding this slice to the cart:

http://opendatacommunities.org/slice?dataset=http%3A%2F%2Fopendatacommunities.org%2Fdata%2Flabour-force%2Funemployment%2Fcount%2Fby-age&http%3A%2F%2Fopendatacommunities.org%2Fdef%2Fontology%2Flabour-force%2Funemployment%2Fcount%2FbyAge=http%3A%2F%2Fopendatacommunities.org%2Fdef%2Fconcept%2Fgeneral-concepts%2Fbyage%2F16%2B&http%3A%2F%2Fopendatacommunities.org%2Fdef%2Fontology%2Ftime%2FrefPeriod=http%3A%2F%2Freference.data.gov.uk%2Fid%2Fgregorian-interval%2F2015-04-01T00%3A00%3A00%2FP12M

fails with:

```
2017-02-17 16:38:56,462 WARN              pipeline       job-ce0415b3 req-1e43d733 :: An error occured while executing the pipeline. The destination was not written to.
java.net.URISyntaxException: Illegal character in path at index 68: http://opendatacommunities.org/def/concept/general-concepts/byage/16 
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at publish_my_data.pipelines.cart.common$eval2389$decode_slice_uri__2394$fn__2395$fn__2397.invoke(common.clj:89)
	at clojure.core$map$fn__6881.invoke(core.clj:2726)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:525)
	at clojure.core$seq__6422.invokeStatic(core.clj:137)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__9126.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__9126.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__9072$G__9067__9085.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6704)
	at clojure.core$into.invokeStatic(core.clj:6771)
	at clojure.core$into.invoke(core.clj:6763)
	at publish_my_data.pipelines.cart.common$eval2389$decode_slice_uri__2394$fn__2395.invoke(common.clj:90)
	at publish_my_data.pipelines.cart.common$eval2389$decode_slice_uri__2394.invoke(common.clj:74)
	at clojure.core$map$fn__6881.invoke(core.clj:2726)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:525)
	at clojure.core$seq__6422.invokeStatic(core.clj:137)
	at clojure.core$map$fn__6881.invoke(core.clj:2719)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:525)
	at clojure.core$seq__6422.invokeStatic(core.clj:137)
	at clojure.core$map$fn__6881.invoke(core.clj:2719)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:525)
	at clojure.core$seq__6422.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3106)
	at clojure.core$doall.invokeStatic(core.clj:3121)
	at clojure.core$doall.invoke(core.clj:3121)
	at publish_my_data.pipelines.cart.common$validate_cart_BANG_.invokeStatic(common.clj:241)
	at publish_my_data.pipelines.cart.common$validate_cart_BANG_.invoke(common.clj:235)
	at publish_my_data.pipelines.cart.save_cart$eval3006$save_cart_validate__3011$fn__3015.invoke(save_cart.clj:149)
	at publish_my_data.pipelines.cart.save_cart$eval3006$save_cart_validate__3011.invoke(save_cart.clj:143)
	at publish_my_data.pipelines.cart.save_cart$save_cart.invokeStatic(save_cart.clj:171)
	at publish_my_data.pipelines.cart.save_cart$save_cart.invoke(save_cart.clj:164)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.core$apply.invoke(core.clj:652)
	at grafter_server.resources.metadata.pipeline$try_exec_pipeline.invokeStatic(pipeline.clj:82)
	at grafter_server.resources.metadata.pipeline$try_exec_pipeline.invoke(pipeline.clj:74)
	at grafter_server.resources.import_pipeline$run_pipeline_response.invokeStatic(import_pipeline.clj:19)
	at grafter_server.resources.import_pipeline$run_pipeline_response.invoke(import_pipeline.clj:18)
	at grafter_server.resources.import_pipeline$run_pipeline_job$fn__19105.invoke(import_pipeline.clj:27)
	at swirrl_server.async.jobs$wrap_logging_context$fn__3995.invoke(jobs.clj:23)
	at grafter_server.jobs$exec_job_sync_BANG_.invokeStatic(jobs.clj:4)
	at grafter_server.jobs$exec_job_sync_BANG_.invoke(jobs.clj:3)
	at grafter_server.jobs$exec_job_async_BANG_$fn__15716.invoke(jobs.clj:9)
	at clojure.core$binding_conveyor_fn$fn__6772.invoke(core.clj:2020)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ricroberts** [comment]
what the JS posts to the pmd action:
```
{"virtualslices":[{"uri":"http://opendatacommunities.org/slice?dataset=http%3A%2F%2Fopendatacommunities.org%2Fdata%2Flabour-force%2Funemployment%2Fcount%2Fby-age&http%3A%2F%2Fopendatacommunities.org%2Fdef%2Fontology%2Flabour-force%2Funemployment%2Fcount%2FbyAge=http%3A%2F%2Fopendatacommunities.org%2Fdef%2Fconcept%2Fgeneral-concepts%2Fbyage%2F16%2B&http%3A%2F%2Fopendatacommunities.org%2Fdef%2Fontology%2Ftime%2FrefPeriod=http%3A%2F%2Freference.data.gov.uk%2Fid%2Fgregorian-interval%2F2015-04-01T00%3A00%3A00%2FP12M","label":"Reference Period = Year ending 2016-03-31, DCLG - Unemployment count age grouping = 16+","number-of-resources":1,"group-uri":"http://opendatacommunities.org/data/labour-force/unemployment/count/by-age","group-label":"Annual Population Survey - Unemployment count, England, by District, LEP"}],"areas":[],"area-collections":[]}
```

i.e whats in the cart is:
`http://opendatacommunities.org/slice?dataset=http%3A%2F%2Fopendatacommunities.org%2Fdata%2Flabour-force%2Funemployment%2Fcount%2Fby-age&http%3A%2F%2Fopendatacommunities.org%2Fdef%2Fontology%2Flabour-force%2Funemployment%2Fcount%2FbyAge=http%3A%2F%2Fopendatacommunities.org%2Fdef%2Fconcept%2Fgeneral-concepts%2Fbyage%2F16%2B&http%3A%2F%2Fopendatacommunities.org%2Fdef%2Fontology%2Ftime%2FrefPeriod=http%3A%2F%2Freference.data.gov.uk%2Fid%2Fgregorian-interval%2F2015-04-01T00%3A00%3A00%2FP12M` (i.e. the same as i posted above)

**Comment by RickMoynihan** [comment]
Looks like a subtly different encoding issue.  Will open a new ticket #6 for it.
